import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        ink:        '#0d1117',
        paper:      '#f4f5f7',
        white:      '#ffffff',
        clay:       '#C4663A',
        muted:      '#5c6474',
        dim:        '#5c6474',
        faint:      '#8a929e',
        rule:       '#c9ced6',
        blue:       '#1b5e8a',
        'blue-lt':  '#2a7ab0',
        'blue-bg':  '#eef3f7',
        teal:       '#7ec8e3',
        civic:      '#b03a2a',
        health:     '#1a6b56',
        'health-lt':'#e4f2ed',
        'health-dk':'#0a2a22',
        families:   '#1e4d7a',
        hood:       '#4a2870',
        voice:      '#7a2018',
        money:      '#6a4e10',
        planet:     '#1a5030',
        bigger:     '#1a3460',
        learning:   '#2563eb',
        action:     '#dc2626',
        resource:   '#16a34a',
        accountability: '#9333ea',
        sidebar: {
          bg: '#0d1117',
          hover: '#161b22',
          active: '#21262d',
        },
        brand: {
          bg: '#ffffff',
          'bg-alt': '#f4f5f7',
          cream: '#ffffff',
          text: '#0d1117',
          accent: '#1b5e8a',
          'accent-hover': '#164d72',
          muted: '#5c6474',
          'muted-light': '#8a929e',
          border: '#dde1e8',
          card: '#ffffff',
          success: '#16a34a',
          warning: '#6a4e10',
          danger: '#b03a2a',
          dark: '#0d1117',
          sand: '#dde1e8',
          warm: '#8a929e',
        },
        theme: {
          health:       '#1a6b56',
          families:     '#1e4d7a',
          neighborhood: '#4a2870',
          voice:        '#7a2018',
          money:        '#6a4e10',
          planet:       '#1a5030',
          bigger:       '#1a3460',
        },
        center: {
          community:    '#9333ea',
          learning:     '#2563eb',
          resource:     '#16a34a',
          action:       '#dc2626',
        },
      },
      fontFamily: {
        display: ['var(--font-display)', '"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        body:    ['var(--font-body)', '"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        mono:    ['var(--font-mono)', '"Courier New"', 'Courier', 'monospace'],
        sans:    ['var(--font-body)', '"DM Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'micro': ['0.6875rem', { lineHeight: '1.2' }],
        'display': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'headline': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'title': ['1.5rem', { lineHeight: '1.25' }],
      },
      borderRadius: {
        'card': '0',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08)',
        'offset': '2px 2px 0 var(--color-rule)',
        'header': '0 2px 8px rgba(0,0,0,0.06)',
        'drop': '0 2px 6px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
}
export default config
